### ISSUE TITLE
[WEB-540] Recommendations restyle

### ISSUE THREAD

**Issue by x48-crypto** [x48-crypto/yearn-mini#52]
Automatically created from [Linear (#540)](https://linear.app/yearn/issue/WEB-540/recommendations-restyle)

*via LinearSync*

**Comment by turtlemoji** [comment]
Wrong issue (v3 issue, I don't know why it synced to yearn mini) @x48-crypto

**Comment by x48-crypto** [comment]
Comment from [Linear (#540)](https://linear.app/yearn/issue/WEB-540/recommendations-restyle)

@xgambitox review plz

---
*via LinearSync*
